services:
  # database
  mongodb:
    container_name: chat-app-database
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
    env_file:
      - ./.env

  # minio storage
  minio:
    container_name: chat-app-minio
    image: minio/minio:RELEASE.2025-02-03T21-03-04Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: $MINIO_ACCESS_KEY
      MINIO_ROOT_PASSWORD: $MINIO_SECRET_KEY
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    env_file:
      - ./.env

  # nestjs server
  server:
    container_name: chat-app-server
    build:
      context: ./chat-app-server
    ports:
      - $NEST_LOCAL_PORT:$NEST_DOCKER_PORT
    env_file:
      - ./.env
    stdin_open: true
    tty: true
    depends_on:
      - mongodb
      - minio

  # react app
  client:
    container_name: chat-app-client
    build:
      context: ./chat-app-client
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    env_file:
      - ./.env
    stdin_open: true

volumes:
  db:
  minio_data:
